import { z } from 'zod';
import { MIN_STAKE, MAX_STAKE } from '../constants/economics';

// Base Enums & Primitives
export const GameTypeSchema = z.enum(['snake', 'connect4', 'rps']);
export const PlayerRoleSchema = z.enum(['p1', 'p2']);
export const MatchWinnerSchema = z.enum(['p1', 'p2', 'draw']).nullable();
export const ConnectionStateSchema = z.enum(['DISCONNECTED', 'CONNECTING', 'CONNECTED', 'RECONNECTING']);

export const RPSChoiceSchema = z.enum(['rock', 'paper', 'scissors']);
export const RequestIdSchema = z.string().min(1).max(128).regex(/^[A-Za-z0-9._:-]+$/, 'Invalid requestId format');

// Client Message Schemas
export const AuthPayloadSchema = z.object({
  telegramId: z.number().int().positive(),
  initData: z.string().max(32768).optional(),
  playerName: z.string().trim().min(1).max(128),
  avatarUrl: z.string().max(2048).optional(),
});

export const JoinRoomPayloadSchema = z.object({
  roomCode: z.string().trim().min(2).max(32),
  telegramId: z.number().int().positive().optional(),
  playerName: z.string().trim().min(1).max(128).optional(),
  avatarUrl: z.string().max(2048).optional(),
});

export const LeaveRoomPayloadSchema = z.object({
  roomCode: z.string(),
});

export const SyncRoomPayloadSchema = z.object({
  roomCode: z.string(),
});

export const RollDicePayloadSchema = z.object({
  roomCode: z.string(),
});

export const DropDiscPayloadSchema = z.object({
  roomCode: z.string(),
  column: z.number().min(0).max(6),
});

export const ChooseRPSPayloadSchema = z.object({
  roomCode: z.string(),
  choice: RPSChoiceSchema,
});

export const RematchRequestPayloadSchema = z.object({
  roomCode: z.string(),
});

export const RematchAcceptPayloadSchema = z.object({
  roomCode: z.string(),
});

export const EmotePayloadSchema = z.object({
  roomCode: z.string().trim().min(2).max(32),
  emoji: z.string().trim().min(1).max(8),
});

export const PingPayloadSchema = z.object({
  timestamp: z.number(),
});

export const CreateRoomPayloadSchema = z.object({
  // Room codes are generated by the server unless a caller supplies a
  // test/invite code. Keeping generation server-owned prevents collisions
  // and makes the browser create flow independent of client timing.
  roomCode: z.string().trim().min(3).max(32).optional(),
  gameType: GameTypeSchema.optional(),
  stake: z.number().min(MIN_STAKE).max(MAX_STAKE).optional(),
  telegramId: z.number().optional(),
  playerName: z.string().optional(),
  avatarUrl: z.string().optional(),
});

export const CancelRoomPayloadSchema = z.object({
  roomCode: z.string(),
  telegramId: z.number().optional(),
});

export const CreateDepositIntentPayloadSchema = z.object({
  amountNano: z.string().regex(/^\d+$/, 'amountNano must be an integer string').max(32),
  walletAddress: z.string().trim().min(10).max(128).optional(),
});

export const SubmitDepositPayloadSchema = z.object({
  intentId: z.string().optional(),
  walletAddress: z.string().trim().min(10).max(128),
  depositAddress: z.string().trim().min(10).max(128),
  amountNano: z.string().regex(/^\d+$/, 'amountNano must be an integer string').max(32),
  boc: z.string().trim().min(1).max(250_000),
  network: z.enum(['mainnet', 'testnet']),
});

export const SubmitWithdrawalPayloadSchema = z.object({
  walletAddress: z.string().trim().min(10).max(128),
  amountNano: z.string().regex(/^\d+$/, 'amountNano must be an integer string').max(32),
});

export const JoinQueuePayloadSchema = z.object({
  gameType: GameTypeSchema.optional(),
  stake: z.number().min(MIN_STAKE).max(MAX_STAKE).optional(),
  telegramId: z.number().optional(),
  playerName: z.string().optional(),
  avatarUrl: z.string().optional(),
});

export const CancelDepositIntentPayloadSchema = z.object({
  intentId: z.string(),
});

// Client Message Union Schema
export const ClientMessageSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('AUTH'), requestId: RequestIdSchema.optional(), payload: AuthPayloadSchema }),
  z.object({ type: z.literal('JOIN_ROOM'), requestId: RequestIdSchema.optional(), payload: JoinRoomPayloadSchema }),
  z.object({ type: z.literal('LEAVE_ROOM'), requestId: RequestIdSchema.optional(), payload: LeaveRoomPayloadSchema }),
  z.object({ type: z.literal('SYNC_ROOM'), requestId: RequestIdSchema.optional(), payload: SyncRoomPayloadSchema }),
  z.object({ type: z.literal('ROLL_DICE'), requestId: RequestIdSchema.optional(), payload: RollDicePayloadSchema }),
  z.object({ type: z.literal('DROP_DISC'), requestId: RequestIdSchema.optional(), payload: DropDiscPayloadSchema }),
  z.object({ type: z.literal('CHOOSE_RPS'), requestId: RequestIdSchema.optional(), payload: ChooseRPSPayloadSchema }),
  z.object({ type: z.literal('REMATCH_REQUEST'), requestId: RequestIdSchema.optional(), payload: RematchRequestPayloadSchema }),
  z.object({ type: z.literal('REMATCH_ACCEPT'), requestId: RequestIdSchema.optional(), payload: RematchAcceptPayloadSchema }),
  z.object({ type: z.literal('EMOTE'), requestId: RequestIdSchema.optional(), payload: EmotePayloadSchema }),
  z.object({ type: z.literal('PING'), requestId: RequestIdSchema.optional(), payload: PingPayloadSchema }),
  z.object({ type: z.literal('GET_ROOMS'), requestId: RequestIdSchema.optional(), payload: z.record(z.string(), z.unknown()).optional() }),
  z.object({ type: z.literal('CREATE_ROOM'), requestId: RequestIdSchema.optional(), payload: CreateRoomPayloadSchema }),
  z.object({ type: z.literal('CANCEL_ROOM'), requestId: RequestIdSchema.optional(), payload: CancelRoomPayloadSchema }),
  z.object({ type: z.literal('CREATE_DEPOSIT_INTENT'), requestId: RequestIdSchema.optional(), payload: CreateDepositIntentPayloadSchema }),
  z.object({ type: z.literal('CANCEL_DEPOSIT_INTENT'), requestId: RequestIdSchema.optional(), payload: CancelDepositIntentPayloadSchema }),
  z.object({ type: z.literal('SUBMIT_DEPOSIT'), requestId: RequestIdSchema.optional(), payload: SubmitDepositPayloadSchema }),
  z.object({ type: z.literal('SUBMIT_WITHDRAWAL'), requestId: RequestIdSchema.optional(), payload: SubmitWithdrawalPayloadSchema }),
  z.object({ type: z.literal('JOIN_QUEUE'), requestId: RequestIdSchema.optional(), payload: JoinQueuePayloadSchema }),
  z.object({ type: z.literal('CANCEL_QUEUE'), requestId: RequestIdSchema.optional(), payload: z.record(z.string(), z.unknown()).optional() }),
]);

// Server Message Schemas
export const RoomPlayerStateSchema = z.object({
  id: PlayerRoleSchema,
  telegramId: z.number().optional(),
  name: z.string(),
  avatarUrl: z.string().optional(),
  isReady: z.boolean(),
  isBot: z.boolean().optional(),
  isConnected: z.boolean().optional(),
});

export const RoomStatePayloadSchema = z.object({
  code: z.string(),
  roomCode: z.string().optional(),
  gameType: GameTypeSchema,
  status: z.enum(['waiting', 'playing', 'gameover']),
  stakeAmount: z.number(),
  potAmount: z.number(),
  p1: RoomPlayerStateSchema.nullable(),
  p2: RoomPlayerStateSchema.nullable(),
  activePlayer: PlayerRoleSchema.nullable().optional(),
  turnPhase: z.string().optional(),
  winner: MatchWinnerSchema.nullable().optional(),
  settlementStatus: z.enum(['pending', 'committed', 'failed']).optional(),
  version: z.number(),
  gameState: z.record(z.string(), z.unknown()),
});

export const DiceRolledPayloadSchema = z.object({
  roomCode: z.string().trim().min(2).max(32),
  player: PlayerRoleSchema,
  value: z.number().min(1).max(6),
  from: z.number(),
  to: z.number(),
  snakeOrLadder: z.object({
    type: z.enum(['snake', 'ladder']),
    from: z.number(),
    to: z.number(),
  }).optional(),
  nextPlayer: PlayerRoleSchema,
  isWinner: z.boolean(),
  version: z.number(),
});

export const DiscDroppedPayloadSchema = z.object({
  roomCode: z.string().trim().min(2).max(32),
  player: PlayerRoleSchema,
  row: z.number().min(0).max(5),
  col: z.number().min(0).max(6),
  board: z.array(z.array(PlayerRoleSchema.nullable())),
  nextPlayer: PlayerRoleSchema,
  winner: MatchWinnerSchema,
  winningCells: z.array(z.object({ row: z.number(), col: z.number() })).optional(),
  version: z.number(),
});

export const RPSRoundResolvedPayloadSchema = z.object({
  roomCode: z.string().trim().min(2).max(32),
  round: z.number(),
  nextRound: z.number().optional(),
  p1Choice: RPSChoiceSchema,
  p2Choice: RPSChoiceSchema,
  roundWinner: z.enum(['p1', 'p2', 'draw']),
  p1Score: z.number(),
  p2Score: z.number(),
  matchWinner: MatchWinnerSchema,
  version: z.number(),
});

export const RematchFailedPayloadSchema = z.object({
  roomCode: z.string(),
  reason: z.string(),
  timestamp: z.number().optional(),
});

export const RPSChoiceCommittedPayloadSchema = z.object({
  roomCode: z.string().trim().min(2).max(32),
  player: PlayerRoleSchema,
  round: z.number(),
  version: z.number(),
});

export const GameOverPayloadSchema = z.object({
  roomCode: z.string(),
  winner: MatchWinnerSchema,
  potAmount: z.number(),
  winnerPayout: z.number(),
  loserPayout: z.number(),
  arenaFee: z.number(),
  xpEarned: z.number(),
  version: z.number(),
  isForfeit: z.boolean().optional(),
  settlementStatus: z.enum(['pending', 'committed', 'failed']).optional(),
});

export const ErrorPayloadSchema = z.object({
  code: z.string(),
  message: z.string(),
  requestId: z.string().optional(),
});

export const SettlementPendingPayloadSchema = z.object({
  roomCode: z.string(),
  winner: MatchWinnerSchema,
  settlementStatus: z.literal('failed').optional(),
  version: z.number(),
});

export const PendingTransactionSchema = z.object({
  id: z.string(),
  type: z.enum(['deposit', 'withdraw', 'match_stake', 'match_win', 'match_draw_refund', 'match_cancelled_refund']),
  amountGram: z.number(),
  status: z.enum(['pending', 'confirmed', 'failed']),
  createdAt: z.string(),
  walletAddress: z.string().optional(),
  network: z.enum(['mainnet', 'testnet']).optional(),
  boc: z.string().optional(),
  txHash: z.string().optional(),
  memo: z.string().optional(),
});

export const DepositIntentCreatedPayloadSchema = z.object({
  intentId: z.string(),
  memo: z.string(),
  depositAddress: z.string(),
  amountNano: z.string(),
  expiresAt: z.string(),
});

export const TransactionConfirmedPayloadSchema = z.object({
  id: z.string(),
  type: z.enum(['deposit', 'withdraw', 'match_stake', 'match_win', 'match_draw_refund', 'match_cancelled_refund']),
  amountGram: z.number(),
  status: z.string(),
  createdAt: z.string(),
  walletAddress: z.string().optional(),
  txHash: z.string().optional(),
  memo: z.string().optional(),
});

export const PongPayloadSchema = z.object({
  timestamp: z.number(),
  clientTimestamp: z.number(),
});

// Server Message Union Schema
export const ServerMessageSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('AUTH_OK'), requestId: z.string().optional(), payload: z.object({ telegramId: z.number(), user: z.record(z.string(), z.unknown()) }) }),
  z.object({ type: z.literal('ACCOUNT_UPDATED'), requestId: z.string().optional(), payload: z.object({ user: z.record(z.string(), z.unknown()) }) }),
  z.object({ type: z.literal('ROOM_STATE'), requestId: z.string().optional(), payload: RoomStatePayloadSchema }),
  z.object({ type: z.literal('GAME_START'), requestId: z.string().optional(), payload: RoomStatePayloadSchema }),
  z.object({ type: z.literal('DICE_ROLLED'), requestId: z.string().optional(), payload: DiceRolledPayloadSchema }),
  z.object({ type: z.literal('DISC_DROPPED'), requestId: z.string().optional(), payload: DiscDroppedPayloadSchema }),
  z.object({ type: z.literal('RPS_ROUND_RESOLVED'), requestId: z.string().optional(), payload: RPSRoundResolvedPayloadSchema }),
  z.object({ type: z.literal('RPS_CHOICE_COMMITTED'), requestId: z.string().optional(), payload: RPSChoiceCommittedPayloadSchema }),
  z.object({ type: z.literal('GAME_OVER'), requestId: z.string().optional(), payload: GameOverPayloadSchema }),
  z.object({ type: z.literal('SETTLEMENT_PENDING'), requestId: z.string().optional(), payload: SettlementPendingPayloadSchema }),
  z.object({ type: z.literal('PLAYER_JOINED'), requestId: z.string().optional(), payload: z.object({ player: RoomPlayerStateSchema, version: z.number() }) }),
  z.object({ type: z.literal('PLAYER_DISCONNECTED'), requestId: z.string().optional(), payload: z.object({ player: PlayerRoleSchema, version: z.number(), timeoutMs: z.number().optional() }) }),
  z.object({ type: z.literal('PLAYER_RECONNECTED'), requestId: z.string().optional(), payload: z.object({ player: PlayerRoleSchema, version: z.number() }) }),
  z.object({ type: z.literal('EMOTE'), requestId: z.string().optional(), payload: z.object({ player: PlayerRoleSchema, emoji: z.string() }) }),
  z.object({ type: z.literal('ERROR'), requestId: z.string().optional(), payload: ErrorPayloadSchema }),
  z.object({ type: z.literal('PONG'), requestId: z.string().optional(), payload: PongPayloadSchema }),
  z.object({ type: z.literal('ROOMS_LIST'), requestId: z.string().optional(), rooms: z.array(z.record(z.string(), z.unknown())).optional(), payload: z.record(z.string(), z.unknown()).optional() }),
  z.object({ type: z.literal('ROOM_CREATED'), requestId: z.string().optional(), room: z.record(z.string(), z.unknown()).optional(), payload: z.record(z.string(), z.unknown()).optional() }),
  z.object({ type: z.literal('ROOM_CANCELLED'), requestId: z.string().optional(), roomCode: z.string().optional(), payload: z.record(z.string(), z.unknown()).optional() }),
  z.object({ type: z.literal('QUEUE_JOINED'), requestId: z.string().optional(), status: z.string().optional(), payload: z.record(z.string(), z.unknown()).optional() }),
  z.object({ type: z.literal('QUEUE_CANCELLED'), requestId: z.string().optional(), payload: z.record(z.string(), z.unknown()).optional() }),
  z.object({ type: z.literal('DEPOSIT_INTENT_CREATED'), requestId: z.string().optional(), payload: DepositIntentCreatedPayloadSchema }),
  z.object({ type: z.literal('DEPOSIT_INTENT_CANCELLED'), requestId: z.string().optional(), payload: CancelDepositIntentPayloadSchema }),
  z.object({ type: z.literal('TRANSACTION_PENDING'), requestId: z.string().optional(), payload: PendingTransactionSchema }),
  z.object({ type: z.literal('TRANSACTION_CONFIRMED'), requestId: z.string().optional(), payload: TransactionConfirmedPayloadSchema }),
  z.object({ type: z.literal('REMATCH_FAILED'), requestId: z.string().optional(), payload: RematchFailedPayloadSchema }),
]);
